landmarks:
  - id: 10
    x: 6.6
    y: 1.25
  - id: 15
    x: 3.2
    y: 3.85
  - id: 20
    x: 3.8
    y: 0.1
  - id: 25
    x: 2.0
    y: 0.02
  - id: 30
    x: 2.0
    y: 3.8
  - id: 35
    x: 0.0
    y: 2.4
  - id: 40
    x: 0.0
    y: 4.2
  - id: 45
    x: 0.0
    y: 6.0
  - id: 50
    x: 0.0
    y: 7.2
  - id: 55
    x: 0.1
    y: 9.84
  - id: 60
    x: 2.0
    y: 9.94
  - id: 65
    x: 5.0
    y: 9.94
  - id: 70
    x: 6.6
    y: 9.84
  - id: 75
    x: 6.8
    y: 7.2
  - id: 80
    x: 6.8
    y: 5.1
  - id: 85
    x: 6.8
    y: 3.0